### ISSUE TITLE
Will the code be open source?

### ISSUE THREAD

**Issue by GitZhaoo** [doublestrong/gapslam#1]
Thanks

**Comment by doublestrong** [comment]
Yes, of course. Thanks for your interest. I will upload the code next week.

**Comment by GitZhaoo** [comment]
Thanks! Best Regard.
        
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Qiangqiang ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/2/2023 04:39
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [doublestrong/gapslam] Will the code be open source? (Issue #1)
        
      
    
  
  
Yes, of course. Thanks for your interest. I will upload the code next week.

**Comment by doublestrong** [comment]
hi, i just uploaded the code. I will close the issue for now.
